version: '3.8'

services:
  backend:
    build: ./backend/docker
    ports:
      - "${BACKEND_PORT}:80"
    volumes:
      - ./backend:/srv/web
      - ./var:/srv/var
      - ./temp:/srv/temp
      - ./data:/srv/data
    working_dir: /srv
    env_file: .env

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    working_dir: /app
    env_file: .env
    command: npm start
